name: Build AyuGram Desktop

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write

jobs:
  version:
    name: Check package version
    runs-on: ubuntu-latest
    outputs:
      aur: ${{ steps.aur.outputs.version }}
      continue_build: ${{ steps.continue_build.outputs.continue_build }}
    steps:
      - name: Check AUR version
        id: aur
        run: |
          AUR_URL="https://aur.archlinux.org/rpc/?v=5&type=info&arg=ayugram-desktop"
          AUR_VER=$(curl -s "$AUR_URL" | jq -r ".results[0].Version")
          echo "version=$AUR_VER" >> $GITHUB_OUTPUT
          echo "AUR_VER=$AUR_VER" >> $GITHUB_ENV

      - name: Check latest tag
        run: |
          LATEST_TAG=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Check if build should continue
        id: continue_build
        run: |
          if [ "${{ env.LATEST_TAG }}" = "v${{ env.AUR_VER }}" ] && [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            echo "continue_build=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: version
    if: ${{ needs.version.outputs.continue_build != 'false' }}
    name: Build package
    runs-on: ubuntu-latest
    env:
      AUR_VER: ${{ needs.version.outputs.aur }}
    steps:
      - name: Free disk space (1/3)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Free disk space (2/3)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Free disk space (3/3)
        uses: rokibhasansagar/slimhub_actions@main

      - name: Set swap to 8 GB
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 8

      - name: Build package
        run: |
          curl -fsSL https://get.docker.com -o install-docker.sh
          sudo sh install-docker.sh
          sudo systemctl start docker
          docker run --rm -v $(pwd):/share archlinux:latest bash -euxc "
            pacman-key --init && pacman-key --populate archlinux
            pacman -Syu --noconfirm base-devel git sudo curl jq vulkan-headers openssl ca-certificates fmt coreutils
            yes | pacman -Scc

            useradd -m builder && echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder
            sed -i '/^OPTIONS=/ s/\\bdebug\\b/!debug/' /etc/makepkg.conf

            sudo -u builder bash -c 'git config --global http.sslBackend "openssl" && cd ~ && git clone https://aur.archlinux.org/ayugram-desktop.git && cd ayugram-desktop && makepkg -s --noconfirm'

            mkdir -p /share/pkg
            cp /home/builder/ayugram-desktop/*.pkg.tar.* /share/pkg/
            cd ~ && git clone https://github.com/itsaschoolbus/ayugram-arch.git repo && cd repo
            git remote set-url origin 'https://itsaschoolbus:${{ secrets.GITHUB_TOKEN }}@github.com/itsaschoolbus/ayugram-arch.git'
            git config --global user.name 'github-actions[bot]' && git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            rm *ayugram* && cp /share/pkg/* . && repo-add ayugram.db.tar.gz *zst
            git add . && git commit -m 'ayugram-desktop ${{ env.AUR_VER }}' && git push
          "

      - name: Upload to releases
        uses: softprops/action-gh-release@master
        with:
          files: pkg/*.pkg.tar.*
          tag_name: v${{ env.AUR_VER }}
          name: ayugram-desktop ${{ env.AUR_VER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
