name: Build Prism Launcher (with patches)

on:
  workflow_dispatch:

jobs:
  build-arch:
    name: Build package (Arch Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Check latest tag
        run: |
          echo "URL=https://gitlab.archlinux.org/archlinux/packaging/packages/prismlauncher.git" >> $GITHUB_ENV
          PROJECT_PATH=$(echo "archlinux/packaging/packages/prismlauncher" | sed -e 's/\//%2F/g')
          LATEST_TAG=$(curl -s "https://gitlab.archlinux.org/api/v4/projects/${PROJECT_PATH}/repository/tags" | jq -r '.[0].name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date "+%Y%m%d")" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build package
        run: |
          curl -fsSL https://get.docker.com -o install-docker.sh
          sudo sh install-docker.sh
          sudo systemctl start docker
          docker run --rm -v $(pwd):/share archlinux:latest bash -euxc "
            pacman-key --init && pacman-key --populate archlinux
            pacman -Syu --noconfirm base-devel git sudo curl jq vulkan-headers openssl ca-certificates fmt coreutils jdk17-openjdk pacman-contrib
            yes | pacman -Scc
            useradd -m builder && echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder
            sed -i '/^OPTIONS=/ s/\\bdebug\\b/!debug/' /etc/makepkg.conf
            sudo -u builder bash -c 'git config --global http.sslBackend "openssl" && cd ~ && git clone ${{ env.URL }} && cd prismlauncher && cp /share/patches/* . && ./apply.sh && updpkgsums && makepkg -s --noconfirm'
            mkdir -p /share/pkg && cp /home/builder/prismlauncher/*.pkg.tar.* /share/pkg/
          "

      - name: Upload to releases
        uses: softprops/action-gh-release@master
        with:
          files: pkg/*.pkg.tar.*
          tag_name: ${{ env.LATEST_TAG }}-${{ env.BUILD_TIME }}
          name: prismlauncher-${{ env.LATEST_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu:
    name: Build package (Ubuntu)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build package
        run: |
          echo "BUILD_TIME=$(date "+%Y%m%d")" >> $GITHUB_ENV
          PROJECT_PATH=$(echo "archlinux/packaging/packages/prismlauncher" | sed -e 's/\//%2F/g')
          LATEST_TAG=$(curl -s "https://gitlab.archlinux.org/api/v4/projects/${PROJECT_PATH}/repository/tags" | jq -r '.[0].name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          sudo bash -c "$(curl -fsSL https://pacstall.dev/q/install || wget -q https://pacstall.dev/q/install -O -)"
          sudo apt install build-essential cmake ninja-build extra-cmake-modules pkg-config scdoc qt6-base-dev qt6-image-formats-plugins qt6-networkauth-dev qt6-svg-dev cmark gamemode-dev libarchive-dev libcmark-dev libgl1-mesa-dev libqrencode-dev libtomlplusplus-dev zlib1g-dev openjdk-17-jdk
          cd pacstall
          sudo pacstall -B -I prismlauncher.pacscript --nosandbox

      - name: Upload to releases
        uses: softprops/action-gh-release@master
        with:
          files: pacstall/prismlauncher*.deb
          tag_name: ${{ env.LATEST_TAG }}-${{ env.BUILD_TIME }}
          name: prismlauncher-${{ env.LATEST_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
