name: Build Prism Launcher (with patches)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Free disk space (1/3)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Free disk space (2/3)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Free disk space (3/3)
        uses: rokibhasansagar/slimhub_actions@main

      - name: Set swap to 8 GB
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 8

      - name: Check latest tag
        run: |
          echo "URL=https://gitlab.archlinux.org/archlinux/packaging/packages/prismlauncher.git" >> $GITHUB_ENV
          PROJECT_PATH=$(echo "archlinux/packaging/packages/prismlauncher" | sed -e 's/\//%2F/g')
          LATEST_TAG=$(curl -s "https://gitlab.archlinux.org/api/v4/projects/${PROJECT_PATH}/repository/tags" | jq -r '.[0].name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "BUILD_TIME=$(TZ=UTC date "+%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build package
        run: |
          curl -fsSL https://get.docker.com -o install-docker.sh
          sudo sh install-docker.sh
          sudo systemctl start docker
          docker run --rm -v $(pwd):/share archlinux:latest bash -euxc "
            pacman-key --init && pacman-key --populate archlinux
            pacman -Syu --noconfirm base-devel git sudo curl jq vulkan-headers openssl ca-certificates fmt coreutils jdk17-openjdk
            yes | pacman -Scc
            useradd -m builder && echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder
            sed -i '/^OPTIONS=/ s/\\bdebug\\b/!debug/' /etc/makepkg.conf
            sudo -u builder bash -c 'git config --global http.sslBackend "openssl" && cd ~ && git clone ${{ env.URL }} && cd prismlauncher && cp /share/patches/* . && ./apply.sh && updpkgsums && makepkg -s --noconfirm'
            mkdir -p /share/pkg && cp /home/builder/prismlauncher/*.pkg.tar.* /share/pkg/
          "

      - name: Upload to releases
        uses: softprops/action-gh-release@master
        with:
          files: pkg/*.pkg.tar.*
          tag_name: ${{ env.LATEST_TAG }}-${{ env.BUILD_TIME }}
          name: prismlauncher-${{ env.LATEST_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
