name: Build ayugram-desktop (AUR)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Check version
        run: |
          sudo apt install jq -y
          AUR_URL="https://aur.archlinux.org/rpc/?v=5&type=info&arg=ayugram-desktop"
          AUR_VER=$(curl -s "$AUR_URL" | jq -r ".results[0].Version")

          LATEST_TAG=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)

          echo "AUR_VERSION=$AUR_VER" >> $GITHUB_ENV
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

          if [ "$LATEST_TAG" = "v$AUR_VER" ]; then
            echo "CONTINUE_BUILD=false" >> $GITHUB_ENV
          fi

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        if: ${{ env.CONTINUE_BUILD != 'false' }}
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Set swap to 8GB
        uses: pierotofy/set-swap-space@master
        if: ${{ env.CONTINUE_BUILD != 'false' }}
        with:
          swap-size-gb: 8

      - name: Build pkg
        if: ${{ env.CONTINUE_BUILD != 'false' }}
        run: |
          sudo apt install docker -y
          docker run --rm -v $(pwd):/share archlinux:latest bash -euxc '
            pacman-key --init
            pacman-key --populate archlinux
            pacman -Syu --noconfirm base-devel git sudo curl jq vulkan-headers openssl ca-certificates

            useradd -m builder
            echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
            chmod 0440 /etc/sudoers.d/builder

            git config --global http.sslBackend "openssl"
            sudo -u builder bash -c "
              cd ~
              git clone https://aur.archlinux.org/yay.git
              cd yay && makepkg -si --noconfirm
              yay -S --noconfirm --needed ronn fmt
              yay -S --noconfirm --needed ayugram-desktop
            "

            mkdir -p /share/pkg
            cp /home/builder/.cache/yay/ayugram-desktop/*.pkg.tar.* /share/pkg/
            pacman -Scc --noconfirm
          '

      - name: Upload to releases
        uses: softprops/action-gh-release@v2.3.4
        if: ${{ env.CONTINUE_BUILD != 'false' }}
        with:
          files: pkg/*.pkg.tar.*
          tag_name: v${{ env.AUR_VERSION }}
          name: ayugram-desktop ${{ env.AUR_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
